kind: Service
apiVersion: v1
metadata:
  name: django-service
  namespace: django
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      targetPort: 8000
      port: 8000
  type: NodePort

